// Date: 1/12/2016 3:57:25 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package projectmayhem1983.wheeloftime.item.RubyDagger;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRubyDagger extends ModelBase
{
  //fields
    ModelRenderer Jewel;
    ModelRenderer Hilt;
    ModelRenderer Cross;
    ModelRenderer Blade;
    ModelRenderer Tip;
  
  public ModelRubyDagger()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Jewel = new ModelRenderer(this, 0, 24);
      Jewel.addBox(0F, 0F, 0F, 1, 1, 1);
      Jewel.setRotationPoint(0F, 23F, 0F);
      Jewel.setTextureSize(64, 32);
      Jewel.mirror = true;
      setRotation(Jewel, 0F, 0F, 0F);
      Hilt = new ModelRenderer(this, 0, 8);
      Hilt.addBox(0F, 0F, 0F, 1, 4, 1);
      Hilt.setRotationPoint(0F, 19F, 0F);
      Hilt.setTextureSize(64, 32);
      Hilt.mirror = true;
      setRotation(Hilt, 0F, 0F, 0F);
      Cross = new ModelRenderer(this, 26, 0);
      Cross.addBox(0F, 0F, 0F, 1, 1, 4);
      Cross.setRotationPoint(0F, 18F, -1.5F);
      Cross.setTextureSize(64, 32);
      Cross.mirror = true;
      setRotation(Cross, 0F, 0F, 0F);
      Blade = new ModelRenderer(this, 1, 17);
      Blade.addBox(0F, 0F, 0F, 1, 3, 2);
      Blade.setRotationPoint(0F, 15F, -0.5F);
      Blade.setTextureSize(64, 32);
      Blade.mirror = true;
      setRotation(Blade, 0F, 0F, 0F);
      Tip = new ModelRenderer(this, 18, 0);
      Tip.addBox(0F, 0F, 0F, 1, 2, 1);
      Tip.setRotationPoint(0F, 13F, 0F);
      Tip.setTextureSize(64, 32);
      Tip.mirror = true;
      setRotation(Tip, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Jewel.render(f5);
    Hilt.render(f5);
    Cross.render(f5);
    Blade.render(f5);
    Tip.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
