/*
*** MADE BY MRPONYCAPTAIN'S .SCHEMATIC TO .JAVA CONVERTING TOOL v2.0 ***
*/

package projectmayhem1983.wheeloftime.structures;

import java.util.Random;

import cpw.mods.fml.common.IWorldGenerator;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.gen.feature.WorldGenerator;

public class tinkerwagon extends WorldGenerator implements IWorldGenerator
{
	protected Block[] getValidSpawnBlocks() {
		return new Block[] {
			Blocks.grass,
			Blocks.dirt,
			Blocks.sand
		};
	}

	public boolean locationIsValidSpawn(World world, int i, int j, int k){
		int distanceToAir = 0;
		Block check = world.getBlock(i, j, k);

		while (check != Blocks.air){
			if (distanceToAir > 1){
				return false;
			}

			distanceToAir++;
			check = world.getBlock(i, j + distanceToAir, k);
		}

		j += distanceToAir - 1;

		Block block = world.getBlock(i, j, k);
		Block blockAbove = world.getBlock(i, j+1, k);
		Block blockBelow = world.getBlock(i, j-1, k);
		
		for (Block x : getValidSpawnBlocks()){
			if (blockAbove != Blocks.air){
				return false;
			}
			if (block == x){
				return true;
			}else if (block == Blocks.snow && blockBelow == x){
				return true;
			}
		}
		
		return false;
	}

	public tinkerwagon() { }

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkProvider chunkGenerator, IChunkProvider chunkProvider) { }

	public void setBlock(World world, int x, int y, int z, Block block, int metadata)
	{
		Block b1 = world.getBlock(x, y, z);

		//if(b1.isAir(world, x, y, z) || b1.isLeaves(world, x, y, z))
		{
			world.setBlock(x, y, z, block, metadata, 2);
		}
	}

	public boolean generate(World world, Random rand, int i, int j, int k) {
		//check that each corner is one of the valid spawn blocks
		if(!locationIsValidSpawn(world, i, j, k) || !locationIsValidSpawn(world, i + 7, j, k) || !locationIsValidSpawn(world, i + 7, j, k + 12) || !locationIsValidSpawn(world, i, j, k + 12))
		{
			return false;
		}

		//k = k - 10;
		//i = i - 10;

		this.setBlock(world, i + 0, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 0, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 1, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 4, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 2, j + 0, k + 5, Blocks.stonebrick, 3);
		this.setBlock(world, i + 2, j + 0, k + 6, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 2, j + 0, k + 7, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 2, j + 0, k + 8, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 2, j + 0, k + 9, Blocks.stonebrick, 3);
		this.setBlock(world, i + 2, j + 0, k + 10, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 2, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 4, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 5, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 6, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 7, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 8, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 9, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 10, Blocks.planks, 0);
		this.setBlock(world, i + 2, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 4, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 5, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 6, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 7, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 8, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 9, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 10, Blocks.wool, 9);
		this.setBlock(world, i + 2, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 2, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 2, Blocks.oak_stairs, 2);
		this.setBlock(world, i + 3, j + 0, k + 3, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 4, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 5, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 6, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 7, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 8, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 9, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 10, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 3, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 9, Blocks.bookshelf, 0);
		this.setBlock(world, i + 3, j + 1, k + 10, Blocks.planks, 0);
		this.setBlock(world, i + 3, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 10, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 4, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 5, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 6, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 7, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 8, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 9, Blocks.wool, 9);
		this.setBlock(world, i + 3, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 3, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 2, Blocks.oak_stairs, 2);
		this.setBlock(world, i + 4, j + 0, k + 3, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 4, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 5, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 6, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 7, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 8, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 9, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 10, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 4, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 8, Blocks.bed, 0);
		this.setBlock(world, i + 4, j + 1, k + 9, Blocks.bed, 8);
		this.setBlock(world, i + 4, j + 1, k + 10, Blocks.planks, 0);
		this.setBlock(world, i + 4, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 10, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 4, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 5, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 6, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 7, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 8, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 9, Blocks.wool, 9);
		this.setBlock(world, i + 4, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 4, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 4, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 5, j + 0, k + 5, Blocks.stonebrick, 3);
		this.setBlock(world, i + 5, j + 0, k + 6, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 5, j + 0, k + 7, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 5, j + 0, k + 8, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 5, j + 0, k + 9, Blocks.stonebrick, 3);
		this.setBlock(world, i + 5, j + 0, k + 10, Blocks.wooden_slab, 8);
		this.setBlock(world, i + 5, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 4, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 5, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 6, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 7, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 8, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 9, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 10, Blocks.planks, 0);
		this.setBlock(world, i + 5, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 4, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 5, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 6, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 7, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 8, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 9, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 10, Blocks.wool, 9);
		this.setBlock(world, i + 5, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 5, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 6, j + 5, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 0, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 1, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 2, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 3, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 4, k + 12, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 0, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 1, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 2, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 3, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 4, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 5, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 6, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 7, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 8, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 9, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 10, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 11, Blocks.air, 0);
		this.setBlock(world, i + 7, j + 5, k + 12, Blocks.air, 0);
		world.setBlockMetadataWithNotify(i + 3, j + 1, k + 4, 1, 2);
		world.setBlockMetadataWithNotify(i + 3, j + 2, k + 4, 9, 2);
		world.setBlockMetadataWithNotify(i + 4, j + 1, k + 4, 1, 2);
		world.setBlockMetadataWithNotify(i + 4, j + 2, k + 4, 8, 2);

		return true;
	}
}