// Date: 1/10/2016 5:15:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package projectmayhem1983.wheeloftime.item.Mahalleinir;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMahalleinir extends ModelBase
{
  //fields
    ModelRenderer Handle;
    ModelRenderer BaseKnob;
    ModelRenderer Head;
    ModelRenderer Head2;
  
  public ModelMahalleinir()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Handle = new ModelRenderer(this, 0, 10);
      Handle.addBox(0F, 0F, 0F, 1, 15, 1);
      Handle.setRotationPoint(0F, 7F, 0F);
      Handle.setTextureSize(64, 32);
      Handle.mirror = true;
      setRotation(Handle, 0F, 0F, 0F);
      BaseKnob = new ModelRenderer(this, 0, 0);
      BaseKnob.addBox(0F, 0F, 0F, 2, 1, 2);
      BaseKnob.setRotationPoint(-0.5F, 22F, -0.5F);
      BaseKnob.setTextureSize(64, 32);
      BaseKnob.mirror = true;
      setRotation(BaseKnob, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 10, 0);
      Head.addBox(0F, 0F, 0F, 4, 4, 7);
      Head.setRotationPoint(-1.5F, 3F, -0.5F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Head2 = new ModelRenderer(this, 36, 0);
      Head2.addBox(0F, 0F, 0F, 5, 5, 6);
      Head2.setRotationPoint(-2F, 2.5F, -6.5F);
      Head2.setTextureSize(64, 32);
      Head2.mirror = true;
      setRotation(Head2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Handle.render(f5);
    BaseKnob.render(f5);
    Head.render(f5);
    Head2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
